# Generated by Django 4.1.5 on 2023-01-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajeros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
