# Generated by Django 4.1.5 on 2023-01-31 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajeros', '0002_aboutme_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lugares',
            old_name='subtitulo',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='lugares',
            old_name='cuerpo',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='lugares',
            old_name='titulo',
            new_name='provincia',
        ),
    ]
