# Generated by Django 4.1.5 on 2023-02-03 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajeros', '0003_rename_subtitulo_lugares_ciudad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugares',
            name='owner',
        ),
    ]
